author:
  name: Chris
  image: profile.jpg
  headline: "Automation enthusiast, working hard to stay lazy."
  bio: "Brother Blue comes from a childhood nickname, it stuck for over a decade and Chris is too common to use as a domain ¯\_(ツ)_/¯"